# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Multipeer_Connect' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Multipeer_Connect

pod 'SnapKit', '~> 3.2.0'

end
